version: '3.9'

networks:
  backend:
    driver: bridge

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: e9w86036f78sd9
    volumes:
      - "./database:/var/lib/mysql"
    ports:
      - 3306:3306
    networks:
      - backend
  db_pma:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db
    ports:
      - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: e9w86036f78sd9
      PMA_USER: root
      PMA_PASSWORD: e9w86036f78sd9
    networks:
      - backend
  mail:
    image: mailhog/mailhog:latest
    ports:
      - 8081:8025
    networks:
      - backend
  wspace:
    build:
      context: ./wspace
    tty: true
    depends_on:
      - db
      - mail
    volumes:
      - "../:/var/www"
      - work_home:/home/obeedock
    networks:
      - backend
    ports:
      - 3000:3000
      - 3001:3001  
  nginx:
    build:
      context: ./nginx
    volumes:
      - "../:/var/www"
      - "./nginx/sites:/etc/nginx/sites-available"
      - "./nginx/ssl:/etc/nginx/ssl"
    ports:
      - "80:80"
      - "443:443" 
    depends_on:
      - php-fpm
    networks:
      - backend  
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./php-fpm/php8.0.ini:/usr/local/etc/php.ini
      - "../:/var/www"
    expose:
      - "9000"
    depends_on:
      - wspace
    networks:
      - backend    
volumes:
  work_home:
